source:
  type: 'minicap'
  host: 'localhost'
  port: 1313
  orientation: 90

ocr:
  type: 'paddleocr'
  host: 'localhost'
  port: 8868
  recv_timeout: 10

operation:
  type: 'minitouch'
  host: 'localhost'
  port: 1111

request:
  type: 'http'
  host: '0.0.0.0'
  port: 9000

notify:
  type: 'miao'
  id: 'MIAO_KEY'

player:
  type: 'common'
  pages:
    - name: '弹出窗口-演习次数不足'
      conditions:
        - {pattern: '演习次数不足'}
    - name: '弹出窗口-困难关卡次数不足'
      conditions:
        - {pattern: '困难关卡每日挑战次数已达上限'}
    - name: '主页'
      conditions:
        - {pattern: '出击', x_range: [0.7, 1.], y_range: [0.4, 0.5]}
    - name: '个人信息'
      conditions:
        - {pattern: '个人信息', x_range: [0., 0.3], y_range: [0., 0.2]}
    - name: '出击主页'
      conditions:
        - {pattern: '主线', x_range: [0., 0.5], y_range: [0.5, 1.]}
    - name: '章节选择-普通-1章'
      conditions:
        - {pattern: '第1章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-2章'
      conditions:
        - {pattern: '第2章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-3章'
      conditions:
        - {pattern: '第3章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-4章'
      conditions:
        - {pattern: '第4章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-5章'
      conditions:
        - {pattern: '第5章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-6章'
      conditions:
        - {pattern: '第6章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-7章'
      conditions:
        - {pattern: '第7章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-8章'
      conditions:
        - {pattern: '第8章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-9章'
      conditions:
        - {pattern: '第9章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-10章'
      conditions:
        - {pattern: '第10章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-11章'
      conditions:
        - {pattern: '第11章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-12章'
      conditions:
        - {pattern: '第12章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-普通-13章'
      conditions:
        - {pattern: '第13章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '困难', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-1章'
      conditions:
        - {pattern: '第1章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-2章'
      conditions:
        - {pattern: '第2章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-3章'
      conditions:
        - {pattern: '第3章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-4章'
      conditions:
        - {pattern: '第4章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-5章'
      conditions:
        - {pattern: '第5章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-6章'
      conditions:
        - {pattern: '第6章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-7章'
      conditions:
        - {pattern: '第7章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-8章'
      conditions:
        - {pattern: '第8章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-9章'
      conditions:
        - {pattern: '第9章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-10章'
      conditions:
        - {pattern: '第10章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-11章'
      conditions:
        - {pattern: '第11章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-12章'
      conditions:
        - {pattern: '第12章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '章节选择-困难-13章'
      conditions:
        - {pattern: '第13章', x_range: [0., 0.3], y_range: [0., 0.3]}
        - {pattern: '普通', x_range: [0., 0.2], y_range: [0.8, 1.]}
    - name: '立刻前往'
      conditions:
        - {pattern: '立刻前往', y_range: [0.5, 1]}
    - name: '再次前往'
      conditions:
        - {pattern: '再次前往', y_range: [0.5, 1]}
    - name: '战场'
      conditions:
        - {pattern: '撤退', x_range: [0.5, 1.], y_range: [0.8, 1.]}
        - {pattern: '切换', x_range: [0.5, 1.], y_range: [0.8, 1.]}
        - {pattern: '迎击', x_range: [0.5, 1.], y_range: [0.8, 1.]}
    - name: '战斗中'
      conditions:
        - {pattern: '暂停.*', x_range: [0.8, 1.], y_range: [0., 0.1]}
    - name: '演习主页'
      conditions:
        - {pattern: '演习', x_range: [0., 0.3], y_range: [0., 0.2]}
        - {pattern: '排行榜', x_range: [0.6, 0.8], y_range: [0.8, 1.]}
        - {pattern: '军需补给', x_range: [0.7, 1.], y_range: [0.8, 1.]}
    - name: '演习对手信息'
      conditions:
        - {pattern: '演习对手信息'}
    - name: '编队出击'
      conditions:
        - {pattern: '编队', x_range: [0, 0.3], y_range: [0, 0.1]}
        - {pattern: '出击', x_range: [0.8, 1.], y_range: [0.8, 1.]}
    - name: '战斗评价'
      conditions:
        - {pattern: '战斗评价', x_range: [0.5, 0.7], y_range: [0.4, 0.6]}
    - name: '战斗获得道具'
      conditions:
        - {pattern: '获得道具', x_range: [0.4, 0.6], y_range: [0.3, 0.5]}
    - name: '战斗获得经验'
      conditions:
        - {pattern: '大获全胜|战术碾压|完成任务|作战超时|全军覆没', x_range: [0.1, 0.4], y_range: [0., 0.3]}
        - {pattern: '确定', x_range: [0.7, 1.], y_range: [0.8, 1.]}
    - name: '战斗失败建议'
      conditions:
        - {pattern: '点击关闭', x_range: [0.4, 0.6], y_range: [0.7, 1.]}
        - {pattern: '指挥官可以通过以下方式提升舰队实力', x_range: [0.4, 0.6], y_range: [0.2, 0.5]}
    - name: '对话框-船坞已满'
      conditions:
        - {pattern: '整理', x_range: [0.3, 0.5], y_range: [0.5, 0.7]}
        - {pattern: '拓展', x_range: [0.4, 0.6], y_range: [0.5, 0.7]}
        - {pattern: '强化', x_range: [0.5, 0.7], y_range: [0.5, 0.7]}
    - name: '对话框-低心情状态'
      conditions:
        - {pattern: '.*低心情状态.*', x_range: [0.4, 0.6], y_range: [0.4, 0.5]}
        - {pattern: '确定', x_range: [0.5, 0.7], y_range: [0.5, 0.8]}
    - name: '对话框-暂停战斗'
      conditions:
        - {pattern: '退出战斗', x_range: [0.3, 0.5], y_range: [0.6, 0.8]}
        - {pattern: '继续战斗', x_range: [0.5, 0.7], y_range: [0.6, 0.8]}
    - name: '对话框-应援' # 活动
      conditions:
        - pattern: '知道了'
  modes:
    - name: 'return'
      page_actions:
        - page: '主页'
          actions:
            - {type: 'over'}
        - page: '战斗中'
          actions:
            - {type: 'sleep', time: 3000}
      other_page_actions:
        actions:
          - {type: 'click', point: [0.05, 0.1]}
      undefined_page_actions:
        actions:
          - {type: 'click', point: [0.05, 0.1]}
    - name: '11-4'
      page_actions:
        - page: '主页'
          actions:
            - {type: 'click', pattern: '出击'}
        - page: '个人信息'
          actions:
            - {type: 'click', point: [0.05, 0.1]}
        - page: '出击主页'
          actions:
            - {type: 'click', pattern: '主线'}
        - page: '章节选择-普通-\d章'
          actions:
            - {type: 'click', pattern: '下一章'}
        - page: '章节选择-普通-10章'
          actions:
            - {type: 'click', pattern: '下一章'}
        - page: '章节选择-普通-11章'
          actions:
            - {type: 'click', pattern: '11-4.*'}
        - page: '章节选择-普通-12章'
          actions:
            - {type: 'click', pattern: '上一章'}
        - page: '章节选择-普通-13章'
          actions:
            - {type: 'click', pattern: '上一章'}
        - page: '章节选择-困难-.*'
          actions:
            - {type: 'click', pattern: '普通'}
        - page: '立刻前往'
          actions:
            - {type: 'click', pattern: '立刻前往'}
        - page: '再次前往'
          actions:
            - {type: 'click', pattern: '再次前往'}
        - page: '对话框-应援'
          actions:
            - {type: 'click', pattern: '知道了'}
        - page: '对话框-暂停战斗'
          actions:
            - {type: 'click', pattern: '继续战斗'}
        - page: '战斗中'
          actions:
            - {type: 'sleep', time: 3000}
        - page: '对话框-船坞已满'
          actions:
            - {type: 'over'}
        - page: '对话框-低心情状态'
          actions:
            - {type: 'over'}
    - name: 'hard-10-2'
      page_actions:
        - page: '主页'
          actions:
            - {type: 'click', pattern: '出击'}
        - page: '个人信息'
          actions:
            - {type: 'click', point: [0.05, 0.1]}
        - page: '出击主页'
          actions:
            - {type: 'click', pattern: '主线'}
        - page: '章节选择-普通-.*'
          actions:
            - {type: 'click', pattern: '困难'}
        - page: '章节选择-困难-\d章'
          actions:
            - {type: 'click', pattern: '下一章'}
        - page: '章节选择-困难-10章'
          actions:
            - {type: 'click', pattern: '10-2.*'}
        - page: '章节选择-困难-11章'
          actions:
            - {type: 'click', pattern: '上一章'}
        - page: '章节选择-困难-12章'
          actions:
            - {type: 'click', pattern: '上一章'}
        - page: '立刻前往'
          actions:
            - {type: 'click', pattern: '立刻前往'}
        - page: '再次前往'
          actions:
            - {type: 'click', pattern: '再次前往'}
        - page: '对话框-应援'
          actions:
            - {type: 'click', pattern: '知道了'}
        - page: '对话框-暂停战斗'
          actions:
            - {type: 'click', pattern: '继续战斗'}
        - page: '战斗中'
          actions:
            - {type: 'sleep', time: 3000}
        - page: '弹出窗口-困难关卡次数不足'
          actions:
            - {type: 'over'}
        - page: '对话框-船坞已满'
          actions:
            - {type: 'over'}
        - page: '对话框-低心情状态'
          actions:
            - {type: 'over'}
    - name: 'exercise'
      page_actions:
        - page: '主页'
          actions:
            - {type: 'click', pattern: '出击'}
        - page: '个人信息'
          actions:
            - {type: 'click', point: [0.05, 0.1]}
        - page: '出击主页'
          actions:
            - {type: 'click', pattern: '演习'}
        - page: '演习主页'
          actions:
            - {type: 'click', pattern: '综合实力'}
        - page: '演习对手信息'
          actions:
            - {type: 'click', pattern: '开始演习'}
        - page: '编队出击'
          actions:
            - {type: 'click', pattern: '出击'}
        - page: '战斗评价'
          actions:
            - {type: 'click', pattern: '战斗评价'}
        - page: '战斗获得道具'
          actions:
            - {type: 'click', pattern: '获得道具'}
        - page: '战斗获得经验'
          actions:
            - {type: 'click', pattern: '确定'}
        - page: '战斗失败建议'
          actions:
            - {type: 'click', pattern: '点击关闭'}
        - page: '对话框-暂停战斗'
          actions:
            - {type: 'click', pattern: '继续战斗'}
        - page: '战斗中'
          actions:
            - {type: 'sleep', time: 3000}
        - page: '战场' # '出击'直接进入战场
          actions:
            - {type: 'click', point: [0.05, 0.1]}
        - page: '章节选择-.*'
          actions:
            - {type: 'click', point: [0.05, 0.1]}
        - page: '对话框-低心情状态'
          actions:
            - {type: 'click', point: [0.05, 0.1]}
        - page: '弹出窗口-演习次数不足'
          actions:
            - {type: 'over'}
