source:
  type: 'scrcpy'  # minicap, file
  host: 'localhost'
  port: 22331

ocr:
  type: 'paddleocr'
  host: 'localhost'
  port: 8868
  recv_timeout: 10

operation:
  type: 'scrcpy'  # minitouch, dummy
  host: 'localhost'
  port: 22332

request:
  type: 'http'
  host: '0.0.0.0'
  port: 9000

notify:
  type: 'miao'
  miao_key: 'xxxxxxx'

application:
  interval: 500

players:
  - path: players/blhx.yaml
  - path: players/wyds.yaml
