source:
    ip: 127.0.0.1
    port: 1111
ocr:
    ip: 127.0.0.1
    port: 8868
player:
    pages:
      - conditions:
          - ocr_pattern: test
            x_min: 0
            x_max: 0.5
            y_min: 0.1
            y_max: 0.5
          - ocr_pattern: test2
            x_min: 0
            x_max: 0.5
            y_min: 0.1
            y_max: 0.5
        actions:
          - name: test
operation:
    ip: 127.0.0.1
    port: 11
