ocr:
    ip: 127.0.0.1
    port: 8868
player:
    pages:
      - conditions:
          - ocr_name: test
          - ocr_name: test2
        actions:
          - type: click
            x: 1000
            y: 1200
          - type: sleep
            time: 1000
      - conditions:
          - object_name: obj
        actions:
          - type: move
            x_src: 1000
            y_src: 1100
            x_dst: 100
            y_dst: 100
source:
    ip: 127.0.0.1
    port: 1313
device:
